[build]
  command = "pnpm run build"
  publish = ".next"

[[redirects]]
  from = "https://lyfline.netlify.app/*"
  to = "https://lyfline.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dev.lyfline.id/*"
  to = "https://lyfline.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/id"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/id/*"
  to = "/:splat"
  status = 301
  force = false

[[plugins]]
  package = "@netlify/plugin-nextjs"
